//
// Created by user on 2024-04-02.
//

#ifndef COMPUTER_ARCHITECTURE_WRITE_BACK_INSTRUCTION_H
#define COMPUTER_ARCHITECTURE_WRITE_BACK_INSTRUCTION_H
void write_back_instruction();
#endif //COMPUTER_ARCHITECTURE_WRITE_BACK_INSTRUCTION_H
