//
// Created by user on 2024-04-02.
//

#ifndef COMPUTER_ARCHITECTURE_EXECUTE_INSTRUCTION_H
#define COMPUTER_ARCHITECTURE_EXECUTE_INSTRUCTION_H
void execute_instruction();
#endif //COMPUTER_ARCHITECTURE_EXECUTE_INSTRUCTION_H
